Cleaned up example scripts
* Refactoring
* Removed LSB stuff broken on CentOS
* Fixed return code in bin/oneacct-export-cron

diff --git a/examples/etc/init.d/oneacct-export-sidekiq b/examples/etc/init.d/oneacct-export-sidekiq
--- a/examples/etc/init.d/oneacct-export-sidekiq
+++ b/examples/etc/init.d/oneacct-export-sidekiq
@@ -10,9 +10,6 @@
 # Description:       Start the sidekiq server required by oneacct-export.
 ### END INIT INFO
 
-# source function library
-. /lib/lsb/init-functions
-
 run_dir="/var/run/oneacct-export"
 log_dir="/var/log/oneacct-export"
 conf_dir="/etc/oneacct-export"
@@ -31,6 +28,8 @@ pid_file="$run_dir/sidekiq.init.pid"
 stdout_log="$log_dir/sidekiq.init.stdout.log"
 stderr_log="$log_dir/sidekiq.init.stderr.log"
 
+retval=0
+
 get_pid() {
     cat "$pid_file"
 }
@@ -39,71 +38,87 @@ is_running() {
     [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
 }
 
-case "$1" in
-    start)
+start() {
     if is_running; then
-        log_daemon_msg "Already started"
+        echo "Already started"
     else
-        log_daemon_msg "Starting $name ..."
+        echo "Starting $name ..."
+
         cd "$run_dir"
         sudo -u "$user" RAILS_ENV=production $cmd >> "$stdout_log" 2>> "$stderr_log" &
+
         echo $! > "$pid_file"
         if ! is_running; then
-            log_failure_msg "Unable to start, see $stdout_log and $stderr_log"
-            exit 1
+            echo "Unable to start, see $stdout_log and $stderr_log"
+            retval=1
         else
-            log_success_msg "Started"
+            echo "Started"
         fi
     fi
-    ;;
-    stop)
+}
+
+stop() {
     if is_running; then
-        log_daemon_msg "Stopping $name ..."
+        echo "Stopping $name ..."
+
         kill `get_pid`
-        for i in $(seq 1 10)
-        do
+        for i in $(seq 1 15); do
             if ! is_running; then
                 break
             fi
-
             echo -n "."
             sleep 1
         done
-        echo
 
+        echo
         if is_running; then
-            log_failure_msg "Not stopped; may still be shutting down or shutdown may have failed"
-            exit 1
+            echo "Not stopped; may still be shutting down or shutdown may have failed"
+            retval=1
         else
-            log_success_msg "Stopped"
+            echo "Stopped"
             if [ -f "$pid_file" ]; then
                 rm "$pid_file"
             fi
         fi
     else
-        log_daemon_msg "Not running"
+        echo "Not running"
+        retval=1
     fi
+}
+
+restart(){
+    stop
+
+    if is_running; then
+        echo "Unable to stop, will not attempt to start"
+        retval=1
+    else
+        start
+    fi
+}
+
+case "$1" in
+    start)
+    start
+    ;;
+    stop)
+    stop
     ;;
     restart)
-    $0 stop
-    if is_running; then
-        log_failure_msg "Unable to stop, will not attempt to start"
-        exit 1
-    fi
-    $0 start
+    restart
     ;;
     status)
     if is_running; then
-        log_daemon_msg "Running"
+        echo "Running"
     else
-        log_daemon_msg "Stopped"
-        exit 1
+        echo "Stopped"
+        retval=3
     fi
     ;;
     *)
-    echo "Usage: $0 {start|stop|restart|status}"
-    exit 1
+    echo "Usage: $name {start|stop|restart|status}"
+    retval=1
     ;;
 esac
 
-exit 0
+exit $retval
